apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
  namespace: student-app
type: Opaque
data:
  POSTGRES_DB: c3R1ZGVudGRi 
  POSTGRES_USER: c3R1ZGVudA==
  POSTGRES_PASSWORD: c3R1ZGVudDEyMw==
